name: ml_exam
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - autopep8=1.6.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2020.6.20
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.4.8
  - fontconfig=2.13.1
  - fonttools=4.33.3
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=12.1.0
  - libpng=1.6.37
  - libstdcxx-ng=12.1.0
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1o
  - packaging=21.3
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.4
  - pthread-stubs=0.4
  - pycodestyle=2.8.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - qt=5.9.7
  - readline=8.1.2
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.3
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - ml02450==1.0.0
